apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
  namespace: microproj-sataponn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: api-gateway
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: '8080'
        - name: CONTENT_SERVICE_URL
          value: http://content-service:8080
        - name: SUBSCRIPTION_SERVICE_URL
          value: http://subscription-service:8080
        - name: JAEGER_AGENT_HOST
          value: jaeger-agent.default.svc.cluster.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
  namespace: microproj-sataponn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: user-service
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: '8080'
        - name: AUTH_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: auth-token-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-service
  labels:
    app: subscription-service
  namespace: microproj-sataponn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscription-service
  template:
    metadata:
      labels:
        app: subscription-service
    spec:
      containers:
      - name: subscription-service
        image: subscription-service
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: '8080'
        - name: USER_SERVICE_URL
          value: http://user-service:8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-service
  labels:
    app: content-service
  namespace: microproj-sataponn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-service
  template:
    metadata:
      labels:
        app: content-service
    spec:
      containers:
      - name: content-service
        image: content-service
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: '8080'
        - name: USER_SERVICE_URL
          value: http://user-service:8080
        - name: SUBSCRIPTION_SERVICE_URL
          value: http://subscription-service:8080
        - name: BBC_API_KEY
          valueFrom:
            secretKeyRef:
              name: content-service-secrets
              key: bbc-api-key
        - name: BUZZFEED_API_KEY
          valueFrom:
            secretKeyRef:
              name: content-service-secrets
              key: buzzfeed-api-key