apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
  namespace: microproj-sataponn
data:
  auth-token-secret: cmVhbGF1dGh0b2tlbnNlY3JldAo=
---
apiVersion: v1
kind: Secret
metadata:
  name: content-service-secrets
  namespace: microproj-sataponn
data:
  bbc-api-key: cmVhbGJiY2FwaWtleQo=
  buzzfeed-api-key: cmVhbGJ1enpmZWVkYXBpa2V5Cg==