content-service:
  port: PORT
  jaeger:
    agent-host: JAEGER_AGENT_HOST

  providers:
    bbc:
      api-url: BBC_API_URL
      api-key: BBC_API_KEY
    buzzfeed:
      api-url: BUZZFEED_API_URL
      api-key: BUZZFEED_API_KEY

services:
  subscription-service:
    url: SUBSCRIPTION_SERVICE_URL
  user-service:
    url: USER_SERVICE_URL