content-service:
  port: 8083
  jaeger:
    agent-host: http://localhost

  providers:
    bbc:
      api-url: http://bbc
      api-key: bbctestkey
    buzzfeed:
      api-url: http://buzzfeed
      api-key: buzzfeedtestkey

services:
  subscription-service:
    url: http://localhost:8082
  user-service:
    url: http://localhost:8081